# Test: Get all food items
GET http://localhost:3002/api/food-items HTTP/1.1

###

# Test: Search food items by name
GET http://localhost:3002/api/food-items/search?name=Banana HTTP/1.1

###

# Test: Get food item by ID
GET http://localhost:3002/api/food-items/1 HTTP/1.1

###

# Test: Create a new food item
POST http://localhost:3002/api/food-items HTTP/1.1
Content-Type: application/json

{
  "name": "Burger",
  "quantity": 5
}

###

# Test: Update food item
PUT http://localhost:3002/api/food-items/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Burger",
  "quantity": 10
}

###

# Test: Delete food item
DELETE http://localhost:3002/api/food-items/1 HTTP/1.1
Content-Type: application/json

###
# Test: Get all establishments
GET http://localhost:3002/api/establishments HTTP/1.1

###
# Test: Get all bags
GET http://localhost:3002/api/bags HTTP/1.1

#Test: Get bags by date range
GET http://localhost:3002/api/bags/by-date-range?startDate=2023-01-01&endDate=2023-12-31 HTTP/1.1

### 
#Test: gett All Reservations
GET http://localhost:3002/api/reservations HTTP/1.1

GET http://localhost:3002/api/reservations/1 HTTP/1.1

###
#Test: Get all shooping cart
GET http://localhost:3002/api/shopping-carts HTTP/1.1

### 
#Test: Get all users
GET http://localhost:3002/api/users HTTP/1.1